name: 'dotnet-nuget-package-build-github-action'
description: '.NET NuGet package build & publish GitHub action'
inputs:
  configuration:
    description: >
      Select the target configuration to build.
    required: false
    default: 'Debug'
  output:
    description: >
      Specify the output destination of the built package.
      By default, $RUNNER_TEMP is set.
    required: false
    default: ${{ runner.temp }}
  project:
    description: >
      Specify the project path.
    required: false
    default: ''
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: "upload-cloud"
  color: "orange"