name: '.NET NuGet package build'
description: '.NET NuGet package build & publish GitHub action'
inputs:
  additional-arguments:
    description: >
      Specify additional arguments to be passed to the build command.
    required: false
    default: ''
  api-key:
    description: >
      Specify the API key to be used for delivery.
      By default, $GITHUB_TOKEN is used.
    required: false
    default: ${{ github.token }}
  clean:
    description: >
      Clean workspace before building
    required: false
    default: false
  nologo:
    description: >
      No copyright information is displayed.
    required: false
    default: true
  configuration:
    description: >
      Select the target configuration to build.
    required: false
    default: 'Debug'
  framework:
    description: >
      Select the target framework to build.
    required: false
  output:
    description: >
      Specify the output destination of the built package.
      By default, '' is set.
    required: false
    default: ''
  project:
    description: >
      Specify the project path.
    required: false
    default: ''
  publish:
    description: >
      Specify `true` if the package is to be delivered after build.
      By default, `false` is specified and only build is performed.
    required: false
    default: false
  source:
    description: >
      Specifies the name of the package source to which the NuGet package is to be delivered when delivering a NuGet package.
      Must be specified if `publish` is set to `true`.
    required: false
    default: ''
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: "upload-cloud"
  color: "orange"